### ISSUE TITLE
SendPhoto

### ISSUE THREAD

**Issue by ark-go** [nickname76/telegrambot#2]
May I ask you to show how you can get an InputFile object
from a local file..
well, here's an example of how to send a file from a SendPhoto disk

**Comment by nickname76** [comment]
Use `os.Open(...)` to get file from disk and `telegrambot.FileReader{...}` as **InputFile** object

**Comment by ark-go** [comment]
```
file, err := os.Open(filepath.Join(path, "..", "img-1.jpg"))
	if err != nil {
		log.Println(err)
	}
	b.Api.SendPhoto(&telegrambot.SendPhotoParams{
		ChatID: msg.Chat.ID,
		Photo: &telegrambot.FileReader{
			Name:   "test",
			Reader: file,
		},
	})
```

Thank you!
